### ISSUE TITLE
Siren Control?

### ISSUE THREAD

**Issue by macinspak** [HendrikRoth/node-red-contrib-arlo#5]
I submitted an issue to add Siren on/off to node-arlo here: https://github.com/devbobo/node-arlo/issues/10

As per that ticket, I am using node-red-contrib-arlo which I uses this library.

I wrote https://flows.nodered.org/node/node-red-contrib-alarm which acts as a node-red powered alarm panel. You hook up various sensors to it and sirens and it is your alarm panel. Hue Motion Sensors, zwave door sensors, arlo camera motion, etc can all act as sensors.

I would like to see if I can use the siren in the Arlo base station as the siren for the node-red powered alarm system.

This golang library provides SirenOn/SirenOff commands, so it shouldn't be too hard to figure out how:
https://github.com/jeffreydwalter/arlo/wiki/API-Documentation

Really, I would like to basically trigger an "entrance delay" style "pip, pip" alert and then a full blown internal siren, or just an internal siren if that's the best we can do. But surely they have a warning mode as well as a full blast?

Then you can use that node-arlo function in node-red-contrib-arlo to provide Siren control functions.

Thoughts?

**Comment by jensrossbach** [comment]
I agree, please add possibility to switch on/off the siren of the Arlo base station, thanks!

**Comment by jensrossbach** [comment]
Pull request #7 provides this functionality, please accept.
